# permissions for end users to edit workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: onyxia-onboarding-operator
    app.kubernetes.io/part-of: onyxia-onboarding-operator
    app.kubernetes.io/managed-by: kustomize
  name: workspace-editor-role
rules:
  - apiGroups:
      - onyxia.onyxia.sh
    resources:
      - workspaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - onyxia.onyxia.sh
    resources:
      - workspaces/status
    verbs:
      - get
