apiVersion: onyxia.onyxia.sh/v1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/instance: workspace-sample
    app.kubernetes.io/part-of: onyxia-onboarding-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: onyxia-onboarding-operator
  name: workspace-sample
spec:
  namespace: titi
  quota:
    default:
      "limits.cpu": "20"
      "limits.memory": "20"
    admin:
      "limits.cpu": "30"
  bucket:
    name: bucket-titi
    quota: 100000000
    paths:
      - diffusion
      - sensible
  # TODO(user): Add fields here
